version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - redis
    environment:
      - PORT=80
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEATHER_URL=https://api.api-ninjas.com/v1/weather?city=
      - WEATHER_AUTH=YbdgZf59lSo6VSJ6BaklYQ==xghcOBjyCR8UbPPf
      - REDIS_PAIR_TTL=300
  redis:
    image: "redis:7.2-alpine"
    ports:
    - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
