version: '3'
services:
  app:
    image: "azare242/weather-server:latest"
    ports:
      - "9999:80"
    depends_on:
      - redis
    environment:
      - PORT=
      - REDIS_HOST=
      - REDIS_PORT=
      - WEATHER_URL=
      - WEATHER_AUTH=
      - REDIS_PAIR_TTL=
  redis:
    image: "redis:7.2-alpine"
    ports:
    - "8989:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
