apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-server-deployment
  labels:
    app: weather-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-server
  template:
    metadata:
      labels:
        app: weather-server
    spec:
      containers:
      - name: wather-server
        image: azare242/weather-server:latest
        env:
          - name: PORT
            value:
          - name: REDIS_HOST
            value: 
          - name: REDIS_PORT
            value: 
          - name: WEATHER_URL
            value: 
          - name: WEATHER_AUTH
            value: 
          - name: REDIS_PAIR_TTL
            value: 
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /configs
            name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: my-configmap
