apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  config.yaml: -|
    PORT: 80
    REDIS_HOST: redis
    REDIS_PORT: 6379
    WEATHER_URL: https://api.api-ninjas.com/v1/weather?city=
    WEATHER_AUTH: YbdgZf59lSo6VSJ6BaklYQ==xghcOBjyCR8UbPPf
    REDIS_PAIR_TTL: 300